FROM wsgi-omd
CMD ["/volumeCode/vending/django/Dockerfile/3-django/local/prd/mod_wsgi-express-80/apachectl", "start"]
#ENTRYPOINT ["python"]


#USER mod_wsgi
#ENTRYPOINT ["mod_wsgi-express", "start-server", "/volumeCode/vending/django/localapp/root/root/wsgi.py"] #wsgi.py --port 8000

#COPY ./static /usr/local/apache2/htdocs/
