DATE_FORMAT  = 'Y-m-d'
TIME_FORMAT = 'H:M:S' # H:i
DATETIME_FORMAT = 'Y-m-d H:M:S'
SHORT_DATE_FORMAT = 'Y/m/d'
SHORT_DATETIME_FORMAT = 'Y/m/d P'

YEAR_MONTH_FORMAT = 'F Y'
MONTH_DAY_FORMAT = 'F j'

DATE_INPUT_FORMATS = ('%Y-%m-%d')
TIME_INPUT_FORMATS = ('%H:%M:%S')
DATETIME_INPUT_FORMATS = ('%Y-%m-%d %H:%M:%S')